name: Tests

on:
  # Allow to manually trigger through github API
  workflow_dispatch:

  # Triggers with push to master
  push:
    branches:
      - master

  # Triggers with push to a pr aimed at master
  pull_request:
    branches:
      - master

  schedule:
    # Every day at 7AM UTC
    - cron: '0 07 * * *'

env:

  import-package-name: grakel
  extra-requires: "[dev]"  # "" for no extra_requires

  # https://github.com/eddiebergman/GraKeL/blob/63a2723fc9488257a7c880fa9b5e5cc95ada9f42/ci_scripts/travis/install.sh#L8-L11
  coverage-reqs: "networkx pandas"
  codecov-py: "3.7"

jobs:

  # General unit tests
  source-test:
    name: ${{ matrix.py }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash # Default to using bash on all

    strategy:
      fail-fast: false
      matrix:
        py: ["3.7", "3.8", "3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}

    - name: Install ${{ env.import-package-name }}
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -e ".${{ env.extra-requires }}"

    - name: Tests
      run: |
        nosetests

  # Testing with codecov coverage uploaded
  codecov-test:
    name: codecov-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.codecov-py }}

    - name: Install ${{ env.import-package-name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install -e ".${{ env.extra-requires }}"

    - name: Tests
      run: |
        nosetests --with-coverage --cover-xml --cover-package=${{ env.import-package-name }}

    #
    #- name: Upload coverage
    #  uses: codecov/codecov-action@v3
    #  with:
    #    fail_ci_if_error: true
    #    verbose: true
